databases:
  - name: cosmedtravel
    databaseName: dbcosmedtravel
    user: cosmedtraveluser

services:
  - type: web
    name: cosmedtravel
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cosmedtravel
          property: connectionString
      - key: f03ce6fb45892c4b812b59e5e341439e
        sync: false
